name: Auto build

on:
  push:
    branches:
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: npm install and build
              run: |
                npm install
                npm run build
                env:
                    CI: true
            - name: commit
              run: |
                git config --global user.email chen-rongliang@qq.com
                git config --global user.name chen-rongliang
                git config --global core.quotepath false
                git add .
                git commit -m "update" -a
            - name: push change
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
